language: node_js
node_js:
  - "8"
dist: trusty
branches:
  only:
    - gh-pages
    - /.*/
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
script:
  - nohup npm run start &
  - sleep 3
  - npm run test

# comment to start travis
